chat/urls.py
from django.urls import path
from . import views

app_name = 'cht'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path("retrieval_qa_with_source/", include("retrieval_qa_with_source.urls")),
    path("line_qa_with_gpt_and_dalle/", include("line_qa_with_gpt_and_dalle.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

line_qa_with_gpt_and_dalle/urls.py
from django.urls import path

from . import views

app_name = "line_qa_with_gpt"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    # path("line_webhook/", views.LineWebHookView.as_view(), name="line_webhook"),
]

retrieval_qa_with_source/urls.py
from django.urls import path
from . import views

app_name = 'qa_with_src'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models


class ChatGpt(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    thread = models.CharField(max_length=255)
    role = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

line_qa_with_gpt_and_dalle/models.py
from django.contrib.auth.models import User
from django.db import models


class ChatLogsWithLine(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=255)
    content = models.TextField()
    file_path = models.CharField(max_length=255, null=True)
    invisible = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

retrieval_qa_with_source/models.py
from django.contrib.auth.models import User
from django.db import models


class ChatLogsWithSource(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    thread = models.CharField(max_length=255)
    role = models.CharField(max_length=255)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

line_qa_with_gpt_and_dalle/forms.py
from django import forms


class UserTextForm(forms.Form):
    question = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        for field in self.base_fields.values():
            field.widget.attrs["class"] = "form-control"
            field.widget.attrs["rows"] = 3
        super().__init__(*args, **kwargs)

line_qa_with_gpt_and_dalle/views.py
import json

from django.contrib.auth.models import User
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import FormView
from dotenv import load_dotenv

from line_qa_with_gpt_and_dalle.domain.usecase.llm_service_use_cases import (
    GeminiUseCase,
    OpenAIGptUseCase,
    OpenAIDalleUseCase,
    OpenAITextToSpeechUseCase,
    OpenAISpeechToTextUseCase,
    UseCase,
)
from line_qa_with_gpt_and_dalle.forms import UserTextForm
from line_qa_with_gpt_and_dalle.models import ChatLogsWithLine

# .env ファイルを読み込む
load_dotenv()


class HomeView(FormView):
    template_name = "line_qa_with_gpt_and_dalle/home.html"
    form_class = UserTextForm
    success_url = reverse_lazy("line_qa_with_gpt:home")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        login_user = User.objects.get(pk=1)  # TODO: request.user.id
        context["chat_logs"] = ChatLogsWithLine.objects.filter(
            user=login_user
        ).order_by("created_at")

        return context

    def form_valid(self, form):
        form_data = form.cleaned_data
        login_user = User.objects.get(pk=1)  # TODO: request.user.id

        use_case_type = "OpenAISpeechToText"  # TODO: ドロップダウンでモードを決める？
        use_case: UseCase | None = None
        content: str | None = form_data["question"]
        if use_case_type == "Gemini":
            use_case = GeminiUseCase()
            content = form_data["question"]
        elif use_case_type == "OpenAIGpt":
            # Questionは何を入れてもいい（処理されない）
            use_case = OpenAIGptUseCase()
            content = form_data["question"]
        elif use_case_type == "OpenAIDalle":
            use_case = OpenAIDalleUseCase()
            content = form_data["question"]
        elif use_case_type == "OpenAITextToSpeech":
            use_case = OpenAITextToSpeechUseCase()
            content = form_data["question"]
        elif use_case_type == "OpenAISpeechToText":
            # Questionは何を入れてもいい（処理されない）
            use_case = OpenAISpeechToTextUseCase()
            content = None

        use_case.execute(user=login_user, content=content)

        return super().form_valid(form)


@csrf_exempt
class LineWebHookView(View):
    @staticmethod
    def post(request, *args, **kwargs):
        """ラインの友達追加時に呼び出され、ラインのIDを登録する"""
        request_json = json.loads(request.body.decode("utf-8"))
        events = request_json["events"]

        # If you run the validation from the `LINE DEVELOPERS` screen, `events` will be returned as `[]`
        if events:
            line_user_id = events[0]["source"]["userId"]

            # webhook connection check at fixed id 'dead...beef'
            if line_user_id != "Udeadbeefdeadbeefdeadbeefdeadbeef":
                # follow | unblock
                if events[0]["type"] == "follow":
                    print("ここにきたらdbに追加")
                    # LinePush.objects.create(line_user_id)
                # block
                if events[0]["type"] == "unfollow":
                    print("ここにきたらdbから削除")
                    # LinePush.objects.filter(line_user_id).delete()

        return HttpResponse(status=200)

retrieval_qa_with_source/views.py
from pathlib import Path

from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import FormView

from config.settings import BASE_DIR
from retrieval_qa_with_source.domain.service.gptpdfservice import GptPdfService
from retrieval_qa_with_source.domain.valueobject.pdfdataloader import PdfDataloader
from retrieval_qa_with_source.forms import UserTextForm
from retrieval_qa_with_source.models import ChatLogsWithSource


class HomeView(FormView):
    template_name = "retrieval_qa_with_source/home.html"
    form_class = UserTextForm
    success_url = reverse_lazy("qa_with_src:home")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        login_user = User.objects.get(pk=1)  # TODO: request.user.id
        context["chat_logs"] = ChatLogsWithSource.objects.filter(
            user=login_user
        ).order_by("thread", "created_at")

        return context

    def form_valid(self, form):
        form_data = form.cleaned_data
        login_user = User.objects.get(pk=1)  # TODO: request.user.id

        file_path = (
            Path(BASE_DIR)
            / "retrieval_qa_with_source/tests/domain/valueobject/令和4年版少子化社会対策白書全体版（PDF版）.pdf"
        )
        chat_history = []  # TODO: 過去ログを含めるかどうかは要判断
        gpt_pdf_service = GptPdfService(PdfDataloader(str(file_path)))
        result = gpt_pdf_service.gpt_answer(form_data["question"], chat_history)
        # TODO: うまく改行できてねーなー（一番下にスクロールするのもつけたほうがいいかも...っていうかAjaxだよ）
        source_documents = "<br>".join(
            [doc.metadata["source"] for doc in result["source_documents"]]
        )
        formatted_answer = f'{result["answer"]}<br><br>{source_documents}'
        ChatLogsWithSource.objects.create(
            user=login_user, thread="XXX", role="user", message=form_data["question"]
        )
        ChatLogsWithSource.objects.create(
            user=login_user, thread="XXX", role="assistant", message=formatted_answer
        )

        return super().form_valid(form)

chat/templates/chat/home.html
{% extends 'chat/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">ChatGPT</h1>
            <p class="lead">The system that forms the basis of work</p>
            <hr class="my-4">
            <p>You can issue ChatGPT.</p>
        </div>

        {% for chatlog in chatlogs %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ chatlog.role }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ chatlog.thread }}</h6>
                    <p class="card-text">{{ chatlog.message }}</p>
                    <a href="#" class="card-link">Card link</a>
                    <a href="#" class="card-link">Another link</a>
                </div>
            </div>
        {% endfor %}
        <form action="{% url 'cht:home' %}" method="POST">
            {{ form }}
            {% csrf_token %}
            <input type="submit" value="送信">
        </form>
    </div>
{% endblock %}

line_qa_with_gpt_and_dalle/templates/line_qa_with_gpt_and_dalle/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ChatGPT-playground</title>

    <!-- bootstrap and css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'chat/css/home.css' %}">

    <!-- font -->
    <link href="https://fonts.googleapis.com/css?family=Sawarabi+Gothic" rel="stylesheet">
    <!-- fontawesome -->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'chat/c_g.ico' %}">

</head>
<body>
    <!-- nav -->
    <h1></h1>

    <div id="main">
        {% block content %}{% endblock %}
    </div>

    <footer>
        <p>© 2019 henojiya. / <a href="https://github.com/duri0214" target="_blank">github portfolio</a></p>
    </footer>
</body>
</html>

line_qa_with_gpt_and_dalle/templates/line_qa_with_gpt_and_dalle/home.html
{% extends 'line_qa_with_gpt_and_dalle/base.html' %}
{% load static %}
{% load split_ext %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">LINE QA with ChatGPT4 and Dall-e-3</h1>
            <p class="lead">The system that forms the basis of work</p>
            <hr class="my-4">
            <p>You can talk with ChatGPT4 and Dall-e-3 using LINE.</p>
        </div>

        {% for chat_log in chat_logs %}
            {% if not chat_log.invisible %}
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ chat_log.role }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted">file: {{ chat_log.file_path }}</h6>
                        <p class="card-text">{{ chat_log.content }}</p>
                        {% if chat_log.file_path|split_ext == "jpg" %}
                            <img src="{{ chat_log.file_path }}" class="img-fluid" alt="Responsive image">
                        {% elif chat_log.file_path|split_ext == "mp3" %}
                            <audio controls>
                                <source src="{{ chat_log.file_path }}" type="audio/mpeg">
                                Your browser does not support the audio element.
                            </audio>
                        {% endif %}
                        <div>
                            <a href="#" class="card-link">Card link</a>
                            <a href="#" class="card-link">Another link</a>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        <form action="{% url 'line_qa_with_gpt:home' %}" method="POST">
            {{ form }}
            {% csrf_token %}
            <input class="mt-3" type="submit" value="送信">
        </form>
    </div>
    <script type="text/javascript">
        window.scrollTo(0, document.body.scrollHeight);
    </script>
{% endblock %}

retrieval_qa_with_source/templates/retrieval_qa_with_source/home.html
{% extends 'retrieval_qa_with_source/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1 class="display-4">ChatGPT with source</h1>
            <p class="lead">The system that forms the basis of work</p>
            <hr class="my-4">
            <p>You can talk with ChatGPT.</p>
        </div>

        {% for chat_log in chat_logs %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ chat_log.role }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ chat_log.thread }}</h6>
                    <p class="card-text">{{ chat_log.message }}</p>
                    <a href="#" class="card-link">Card link</a>
                    <a href="#" class="card-link">Another link</a>
                </div>
            </div>
        {% endfor %}
        <form action="{% url 'qa_with_src:home' %}" method="POST">
            {{ form }}
            {% csrf_token %}
            <input class="mt-3" type="submit" value="送信">
        </form>
    </div>
    <script type="text/javascript">
        window.scrollTo(0, document.body.scrollHeight);
    </script>
{% endblock %}